"""Helper library for MBTI questions"""
# pylint: disable=line-too-long
from typing import Final
from enum import Enum

class Emotions(Enum):
    """Represents the different emotions as prefixes to user questions"""

    AMAZED: Final[str] = "I am amazed."
    ANGRY: Final[str] = "I am angry."
    BOILING: Final[str] = "I am boiling with anger."
    BORED: Final[str] = "I am bored."
    IMPRESSED: Final[str] = "I am feeling impressed."
    LAUGHING: Final[str] = "I am laughing."
    PROUD: Final[str] = "I am proud."
    REMINISCING: Final[str] = "I am reminiscing."
    ADORED: Final[str] = "I feel adoration."
    AFRAID: Final[str] = "I feel afraid."
    AMUSED_EMBARRASSED: Final[str] = "I feel amused and embarrassed."
    AMUSED: Final[str] = "I feel amused."
    ADRENALINE_RUSH: Final[str] = "I feel an adrenaline rush."
    ANGRY_DISGUST: Final[str] = "I feel angry disgust."
    ANNOYED: Final[str] = "I feel annoyed."
    ANXIOUS: Final[str] = "I feel anxious."
    AWED: Final[str] = "I feel awe."
    AWESTRUCK: Final[str] = "I feel awestruck."
    AWKWARD: Final[str] = "I feel awkward."
    CALM: Final[str] = "I feel calm."
    CONFUSED: Final[str] = "I feel confused."
    CURIOUS: Final[str] = "I feel curious."
    CURIOSLY_CONFUSED: Final[str] = "I feel curiously confused."
    DEEP_RELIEF: Final[str] = "I feel deep relief."
    DESIRE: Final[str] = "I feel desire."
    DISGUSTED: Final[str] = "I feel disgusted."
    EMBARRASSED: Final[str] = "I feel embarrassed."
    EXCITED: Final[str] = "I feel excited."
    EXTREME_DISGUST: Final[str] = "I feel extreme disgust."
    EXTREME_FEAR: Final[str] = "I feel extreme fear."
    EXTREMELY_HAPPY: Final[str] = "I feel extremely happy."
    EXTREMELY_SAD: Final[str] = "I feel extremely sad."
    FEAR: Final[str] = "I feel fear."
    GROSSED_OUT: Final[str] = "I feel grossed out."
    HAPPY: Final[str] = "I feel happy."
    HORNY: Final[str] = "I feel horny."
    HORROR: Final[str] = "I feel horror."
    HUNGER: Final[str] = "I feel hunger."
    NARROWLY_ESCAPED: Final[str] = "I feel I narrowly escaped."
    INTERESTED: Final[str] = "I feel interested."
    INTRIGUED: Final[str] = "I feel intrigued."
    LOVE: Final[str] = "I feel love."
    HUNGER_SATISFIED: Final[str] = "I feel my hunger is satisfied."
    NERVOUS: Final[str] = "I feel nervous."
    NOSTALGIC: Final[str] = "I feel nostalgic."
    OTHERS_PAIN: Final[str] = "I feel others' pain."
    PAIN: Final[str] = "I feel pain."
    PEACEFUL: Final[str] = "I feel peaceful."
    RELIEF: Final[str] = "I feel relief."
    ROMANTIC_LOVE: Final[str] = "I feel romantic love."
    ROMANTIC: Final[str] = "I feel romantic."
    SAD: Final[str] = "I feel sad."
    SATISFIED: Final[str] = "I feel satisfied."
    SCARED: Final[str] = "I feel scared."
    SERENE: Final[str] = "I feel serene."
    SEXUAL_DESIRE: Final[str] = "I feel sexual desire."
    SEXUALLY_AROUSED: Final[str] = "I feel sexually aroused."
    SHOCKED: Final[str] = "I feel shocked."
    SURPRISED: Final[str] = "I feel surprised."
    SYMPATHY: Final[str] = "I feel sympathy."
    WONDER: Final[str] = "I feel wonder."
    HUMOROUS: Final[str] = "I find this humorous."
